name: Sync BanAd_mini Rule

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # 每天 00:00 UTC 执行

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download BanAd_mini JSON, a-dove-is-dumb.yaml and ADs_merged.txt
        run: |
          mkdir -p temp_repo
          mkdir -p rules
          curl -L raw.githubusercontent.com/TG-Twilight/AWAvenue-Ads-Rule/refs/heads/main/Filters/AWAvenue-Ads-Rule-Singbox.json -o temp_repo/banAd_mini.json
          curl -L raw.githubusercontent.com/ignaciocastro/a-dove-is-dumb/refs/heads/main/clash.yaml -o temp_repo/a-dove-is-dumb.yaml
          curl -L raw.githubusercontent.com/wuiiled/Wuiiled_Setup/refs/heads/mihomo/rules/ADs_merged.txt -o temp_repo/ADs_merged.txt

      - name: Install dependencies
        run: npm install fs-extra yaml

      - name: Merge banAd_mini.json + a-dove-is-dumb.yaml + ADs_merged.txt
        run: |
          node <<'EOF'
          const fs = require('fs-extra');
          const path = require('path');
          const YAML = require('yaml');

          (async () => {
            try {
              const miniPath = 'temp_repo/banAd_mini.json';
              const adobePath = 'temp_repo/a-dove-is-dumb.yaml';
              const adsMergedPath = 'temp_repo/ADs_merged.txt';
              const outputPath = 'rules/banAd_mini.json';

              let miniData = {};
              if (await fs.pathExists(miniPath)) {
                miniData = JSON.parse(await fs.readFile(miniPath, 'utf8')) || {};
              }

              const combined = { domain: [], domain_suffix: [], domain_regex: [] };

              if (Array.isArray(miniData.rules)) {
                for (const rule of miniData.rules) {
                  if (Array.isArray(rule.domain)) combined.domain.push(...rule.domain);
                  if (Array.isArray(rule.domain_suffix)) combined.domain_suffix.push(...rule.domain_suffix);
                  if (Array.isArray(rule.domain_regex)) combined.domain_regex.push(...rule.domain_regex);
                }
              }

              const normalizeLine = (raw) => {
                if (!raw || typeof raw !== 'string') return '';
                let s = raw.trim();
                s = s.replace(/^\uFEFF/, '');
                return s;
              };

              const handleLineByPrefix = (line) => {
                const mDomain = line.match(/^\s*DOMAIN\s*[,：:]\s*(.+)$/i);
               if (mDomain) {
                  const val = mDomain[1].trim();
                  if (val.startsWith('*.')) combined.domain_suffix.push(val.slice(2));
                  else if (/^[A-Za-z0-9.-]+$/.test(val)) combined.domain.push(val);
                  else combined.domain.push(val);
                  return true;
                }
                const mSuffix = line.match(/^\s*DOMAIN-SUFFIX\s*[,：:]\s*(.+)$/i);
                if (mSuffix) {
                  const val = mSuffix[1].trim().replace(/^\./, '');
                  combined.domain_suffix.push(val);
                  return true;
                }
                const mRegex = line.match(/^\s*DOMAIN-REGEX\s*[,：:]\s*(.+)$/i);
                if (mRegex) {
                  combined.domain_regex.push(mRegex[1].trim());
                  return true;
                }
                return false;
              };

              const genericParseLine = (rawLine) => {
                let line = normalizeLine(rawLine);
                if (!line) return;
                if (handleLineByPrefix(line)) return;

                line = line.replace(/^(\s*(DOMAIN|DOMAIN-SUFFIX|DOMAIN-REGEX)\s*[,：:]\s*)+/i, '').trim();

                if (line.startsWith('*.')) {
                  combined.domain_suffix.push(line.slice(2));
                  return;
                }

                if (/^[A-Za-z0-9.-]+$/.test(line)) {
                  combined.domain.push(line);
                  return;
                }

                const parts = line.split(',').map(p => p.trim()).filter(Boolean);
                if (parts.length) {
                  const candidate = parts[parts.length - 1];
                  if (!candidate) return;
                  if (candidate.startsWith('*.')) {
                    combined.domain_suffix.push(candidate.slice(2));
                  } else if (/^[A-Za-z0-9.-]+$/.test(candidate)) {
                    combined.domain.push(candidate);
                  } else {
                    combined.domain.push(candidate);
                  }
                }
              };

              // 解析 a-dove-is-dumb.yaml
              if (await fs.pathExists(adobePath)) {
                const yamlContent = await fs.readFile(adobePath, 'utf8');
                let parsed = {};
                try { parsed = YAML.parse(yamlContent) || {}; } catch (e) { parsed = {}; }

                if (Array.isArray(parsed.payload) && parsed.payload.length) {
                  for (const item of parsed.payload) {
                    genericParseLine(String(item));
                  }
                } else {
                  const lines = yamlContent.split(/\r?\n/).map(l => l.trim()).filter(l => l && !l.startsWith('#'));
                  for (let line of lines) genericParseLine(line);
                }
              }

              // 解析 ADs_merged.txt
              if (await fs.pathExists(adsMergedPath)) {
                const adsContent = await fs.readFile(adsMergedPath, 'utf8');
                const lines = adsContent.split(/\r?\n/).map(l => l.trim()).filter(l => l && !l.startsWith('#'));
                for (let line of lines) genericParseLine(line);
              }

              // 清洗去重、规范化与排序
              for (const key of ['domain', 'domain_suffix', 'domain_regex']) {
                if (!Array.isArray(combined[key])) continue;
                combined[key] = Array.from(new Set(
                  combined[key].filter(d => typeof d === 'string' && d.trim()).map(d => d.trim())
                ));
                if (key === 'domain_suffix') combined[key] = combined[key].map(d => d.replace(/^\./, ''));
                combined[key] = combined[key].sort();
                if (!combined[key].length) delete combined[key];
              }

              const output = { version: 2, rules: [combined] };
              await fs.ensureDir(path.dirname(outputPath));
              await fs.writeJson(outputPath, output, { spaces: 2 });
              console.log(`Merged banAd_mini.json + a-dove-is-dumb.yaml + ADs_merged.txt -> ${outputPath}`);
            } catch (err) {
              console.error(err);
              process.exit(1);
            }
          })();
          EOF

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add rules/banAd_mini.json
          git diff --cached --quiet || (git commit -m "Update banAd_mini.json" && git push)
